# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# This is a Jupyter notebook for exploring the NYC taxi dataset
import pandas as pd

# Load the dataset
df = pd.read_csv('/dbfs/databricks-datasets/nyctaxi/taxizone/taxi_zone_lookup.csv')

# Display the first few rows
display(df)
